- src: geerlingguy.git
- src: geerlingguy.composer
- src: geerlingguy.ruby
- src: geerlingguy.docker
- src: andrewrothstein.terraform
- src: andrewrothstein.curl
- src: anxs.build-essential
- src: xussof.software_software_properties_common
