- name: Install common apps
  hosts: localhost
  become: true
  tasks:
    - name: Enable universe repository
      command: add-apt-repository multiverse
    - name: Install Snapd
      apt:
        name: snapd
