- name: Install common apps
  hosts: localhost
  become: true
  tasks:
    - name: Update apt package list
      apt:
        upgrade: "yes"
        update_cache: yes
    - name: Install Snapd
      apt:
        name: snapd

