- name: Install development apps
  hosts: localhost
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
    - name: Install Git
      apt:
        name: git
    - name: Install GitKraken
      snap:
        name: gitkraken
    - name: VS Code
      snap:
        name: code
        classic: yes
    - name: Install Ruby
      snap:
        name: ruby
        classic: yes
    - name: Install Bundler
      gem:
        name: bundler
    - name: Install Virtualbox
      apt:
        name: virtualbox
    - name: Install Terraform
      snap:
        name: terraform
