- name: Install development apps
  hosts: localhost
  become: true
  vars:
    NODEJS_VERSION: "12"
    ansible_distribution_release: "eoan"
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
    - name: Install Git
      apt:
        name: git
    - name: Install GitKraken
      snap:
        name: gitkraken
    - name: VS Code
      snap:
        name: code
        classic: yes
    - name: Install Ruby
      snap:
        name: ruby
        classic: yes
    - name: Install Bundler
      gem:
        name: bundler
    - name: Install Virtualbox
      apt:
        name: virtualbox
    - name: Install Terraform
      snap:
        name: terraform
    - name: Add Ansible repository
      apt_repository:
        # TODO: Change this after Ansible's PPA will be fixed
        # repo: ppa:ansible/ansible eoan main
        repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu {{ansible_distribution_release}} main
        update_cache: yes
    - name: Install Ansible
      apt:
        name: ansible
    - name: Install Node.js (--classic)
      snap:
        name: node
        classic: yes
        channel: "{{ NODEJS_VERSION }}/stable"
    - name: Install PHP
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - php
        - php-common
        - php-json
        - php-phpdbg
        - php-dev
        - php-xml
        - php-cli
        - libapache2-mod-php
        - php-mysql
        - php-gd
        - php-curl
        - php-mbstring
        - php-zip
        - php-pear
