- name: Install multimedia apps
  hosts: localhost
  become: true
  tasks:
    - name: Install VLC
      apt:
        name: vlc
    - name: Install Ace Stream Player
      snap:
        name: acestreamplayer
    - name: Install SimpleScreenRecorder
      apt:
        name: simplescreenrecorder
    - name: Install Google Play Music Desktop Player
      snap:
        name: google-play-music-desktop-player
    - name: Install OBS Studio
      snap:
        name: obs-studio
    - name: Install Ubuntu Restricted Extras
      apt:
        name: ubuntu-restricted-extras
