- name: Install multimedia apps
  hosts: localhost
  become: true
  tasks:
    - name: Install VLC
      apt:
        name: vlc
    - name: Install SimpleScreenRecorder
      apt:
        name: simplescreenrecorder
    - name: Install Google Play Music Desktop Player
      snap:
        name: google-play-music-desktop-player
