- name: Install work apps
  hosts: localhost
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
    - name: Install Firefox
      apt:
        name: firefox
    - name: Install Chromium
      snap:
        name: chromium
    - name: Install Opera
      snap:
        name: opera
    - name: Add Yandex Browser GPG key
      apt_key:
        url: https://repo.yandex.ru/yandex-browser/YANDEX-BROWSER-KEY.GPG
    - name: Add Yandex Browser repository
      apt_repository:
        repo: deb [arch=amd64] http://repo.yandex.ru/yandex-browser/deb beta main
        update_cache: yes
    - name: Install Yandex Browser
      apt:
        name: yandex-browser-beta
