- name: Install work apps
  hosts: localhost
  become: true
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes
    - name: Install Firefox
      apt:
        name: firefox
    - name: Install Chromium
      snap:
        name: chromium
